export const educationOptions = [
  'High School Diploma',
  "Associate's Degree",
  "Bachelor's Degree",
  "Master's Degree",
  'PhD',
]
export const hobbyOptions = [
  'Coding',
  'Hiking',
  'Gaming',
  'Automation',
  'Drawing',
  'Photography',
  'Reading',
  'Machine Learning Research',
  'Project Planning',
  'Traveling',
]
export const certificateOptions = [
  'PMP Certification (Project Management Professional)',
  'AWS Certified DevOps Engineer',
  'Google Cloud Professional Data Engineer',
  'React Certification (any provider)',
  'Frontend Master Certification',
  'Adobe Photoshop Certified Professional',
  'Cisco Certified Network Associate (CCNA)',
  'Certified Scrum Master (CSM)',
]

export const experienceOptions = [
  'Less than 1 year',
  '1-3 years',
  '3-5 years',
  '5+ years',
]
export const employmentTypeOptions = [
  'Full-time',
  'Part-time',
  'Contract',
  'Internship',
]
export const maritalStatusOptions = ['Single', 'Married', 'Divorced', 'Widowed']

export const skillOptions = [
  'React',
  'Tailwind CSS',
  'Node.js',
  'MongoDB',
  'Python',
  'JavaScript',
  'HTML',
  'CSS',
  'Java',
  'C++',
  'C#',
  'PHP',
  'Ruby',
  'Swift',
  'Go',
  'Rust',
  'Kotlin',
  'TypeScript',
  'SQL',
  'NoSQL',
  'GraphQL',
  'REST',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'Git',
  'GitHub',
  'Bitbucket',
  'Jenkins',
  'Travis CI',
  'CircleCI',
  'Jira',
  'Confluence',
  'Slack',
  'Asana',
  'Trello',
  'Notion',
  'Jjira',
  'Confluence',
  'Slack',
  'Asana',
  'Trello',
  'Notion',
  'Jira',
  'Confluence',
  'Slack',
  'Asana',
  'Trello',
  'Notion',
  'Jira',
  'Confluence',
  'Slack',
  'Asana',
  'Trello',
  'Notion',
]

export const keyForSearch = [
  'title',
  'company',
  'location',
  'job_category',
  'description',
  'employment_type',
  'maritial_status',
  'qualifications',
  'experience',
  'address',
  'name',
  'email',
  'phone',
  'address',
  'previous_company',
  'position',
]
